CREATE
DATABASE tp DEFAULT CHARACTER SET utf8;

CREATE TABLE student
(
    id      INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name    VARCHAR(64) NOT NULL,
    birthAt DATE DEFAULT NULL
);

ALTER TABLE student
    ADD COLUMN height INT(3) DEFAULT NULL;


